tendermint/spn

.github/workflows/semantic-pull-request.yml
=> ci: Added semantic PR GH action

x/genesis/keeper/gprc_query_test.go, x/genesis/types/genesis_file.go, x/genesis/types/genesis_file_test.go
Ensure that when a chain is created, the genesis is empty
=> feat(genesis): prevent creating a chain with a genesis containing existing accounts or gentxs

x/genesis/specs/01_state.md, x/genesis/specs/02_messages.md, x/genesis/specs/README.md
Create the first specification for the `genesis` module based on the implementation of the POC
=> docs(genesis): first specification

x/genesis/handler.go, x/genesis/handler_test.go
#78 
Check and approve the proposal on the "Propose" message if the creator is the coordinator
Some refactoring has been done in the handler
=> feat(genesis): auto approve proposals created by the coordinator

app/app.go, go.sum
Update home directory to adapt to the new standard of Starport
=> fix: update home directory

x/genesis/types/chain.go
Describing isAuthorizedChainID
=> docs: chain.go

Makefile, internal/version/version.go
- Create `Makefile` with useful commands;
- Add version package to print current build version;
```shell
$ make help
```
=> feat(Makefile): Makefile commands and build version

.github/workflows/test-lint.yml, .github/workflows/test-semantic.yml, .github/workflows/test.yml
Create GitHub workflow to run CI tests
- Add unit test workflow;
- Add lint test workflow;
- Add PR semantic test workflow;
=> feat(CI): GitHub workflow for CI tests

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/spn-bug-report.md, .github/ISSUE_TEMPLATE/spn-feature-request.md, .github/PULL_REQUEST_TEMPLATE.md
Create GitHub templates.
- Add bug issue template;
- Add feature issue template;
- Add PR template;
=> feat(.github): GitHub templates

Makefile
we should use starport cli for those.
=> refactor(Makefile): rm unneeded commands

.github/workflows/generate.yml, config.yml
there is a problem with file perms therefore, ci cannot open a pr. this might be fixed in starport's side or here. but let's merge anyway to at least reduce the noise in the next prs.
=> feat(ci): generate code through automated PRs

x/launch/client/cli/query_chain.go, x/launch/client/cli/query_genesis_account.go, x/launch/client/cli/query_genesis_validator.go, x/launch/client/cli/query_request.go, x/launch/client/cli/query_vested_account.go, x/launch/client/cli/tx_create_chain.go, x/launch/client/cli/tx_edit_chain.go, x/launch/client/cli/tx_request_add_account.go, x/launch/client/cli/tx_request_add_validator.go, x/launch/client/cli/tx_request_add_vested_account.go, x/launch/client/cli/tx_request_remove_account.go, x/launch/client/cli/tx_request_remove_validator.go, x/launch/client/cli/tx_revert_launch.go, x/launch/client/cli/tx_trigger_launch.go, x/profile/client/cli/query_coordinator.go, x/profile/client/cli/tx_update_coordinator_address.go
Closes #234
Use kebab-case for argument in CLI
=> refactor(x/**/cli): Use kebab-case for argument in CLI

pkg/errors/critical.go, x/launch/keeper/msg_server_create_chain.go, x/profile/keeper/msg_server_delete_coordinator.go, x/profile/keeper/msg_server_update_coordinator_address.go, x/profile/keeper/msg_server_update_coordinator_description.go
`Criticalf` extends a critical error with additional information. This function works like the Critical function with the additional functionality of formatting the input as specified.
=> feat(pkg/error): create `criticalf` error method for additional information

readme.md
This updates the Discord invite links.
These are the criteria that every PR should meet, please check them off as you
review them:
=> docs: update discord links

x/campaign/client/cli/query_mainnet_account_test.go, x/campaign/client/cli/query_mainnet_vesting_account_test.go, x/campaign/keeper/campaign_chains_test.go, x/campaign/keeper/campaign_test.go, x/campaign/keeper/grpc_query_campaign_test.go, x/campaign/keeper/grpc_query_mainnet_account_test.go, x/campaign/keeper/mainnet_account_test.go, x/campaign/keeper/mainnet_vesting_account_test.go, x/launch/client/cli/query_chain_test.go, x/launch/client/cli/query_genesis_account_test.go, x/launch/client/cli/query_genesis_validator_test.go, x/launch/client/cli/query_request_test.go, x/launch/client/cli/query_vesting_account_test.go, x/launch/keeper/genesis_account_test.go, x/launch/keeper/genesis_validator_test.go, x/launch/keeper/grpc_query_chain_test.go, x/launch/keeper/grpc_query_genesis_account_test.go, x/launch/keeper/grpc_query_genesis_validator_test.go, x/launch/keeper/grpc_query_request_test.go, x/launch/keeper/grpc_query_vesting_account_test.go, x/launch/keeper/request_test.go, x/launch/keeper/vesting_account_test.go, x/profile/client/cli/query_coordinator_test.go, x/profile/client/cli/query_validator_test.go, x/profile/keeper/coordinator_by_address_test.go, x/profile/keeper/coordinator_test.go, x/profile/keeper/grpc_query_coordinator_test.go
- Check if the paginated result is a subset of all messages; 
- Check element from get all methods matches independently of the sort;
=> refactor(test): improve test templates

proto/launch/tx.proto, x/launch/keeper/msg_server_request_add_account.go, x/launch/keeper/msg_server_request_add_validator.go, x/launch/keeper/msg_server_request_add_vesting_account.go, x/launch/keeper/msg_server_request_remove_account.go, x/launch/keeper/msg_server_request_remove_validator.go, x/launch/types/tx.pb.go
=> fix: returns unique Tx response per Tx

.github/CODEOWNERS
=> chore: add @ivanovpetr to CODEOWNERS

readme.md
Fixes the incorrect doc link and adds a few other links 
- [x ] Update documentation (*.md) (if needed)
=> docs: fix doc link and add a few other helpful links

.github/CODEOWNERS
Adds me as a codeowner :).
These are the criteria that every PR should meet, please check them off as you
review them:
=> chore: add @aljo242 CODEOWNER

.github/CODEOWNERS
Add @giunatale as code owner
*N.A.*
*N.A.*
=> chore: add @giunatale as code owner

x/campaign/types/message_add_vesting_options.go, x/monitoringc/client/cli/tx.go, x/monitoringp/client/cli/tx.go, x/monitoringp/handler.go, x/monitoringp/keeper/monitoring_packet.go
Remove some unused vars and switch to fix lint messages
=> fix: remove unused logic for lint issues

x/profile/types/genesis.go, x/profile/types/genesis_test.go
=> fix(`profile`): check `coordByAddress` is associated to an active coordinator in genesis valdiate

x/monitoringc/keeper/msg_server_create_client.go, x/monitoringp/keeper/begin_block.go, x/monitoringp/keeper/consumer_client.go, x/monitoringp/keeper/monitoring_packet.go
=> chore: remove outdated TODO comments

.github/workflows/reset-testnet.yml
Closes #602.
This PR adds an action to reset a testnet state.
Go into `Actions` menu and manually trigger the action.
=> ci(reset-testnet): add action to reset testnet state

x/participation/client/cli/query_used_allocations_test.go, x/participation/keeper/grpc_used_allocations.go, x/participation/keeper/grpc_used_allocations_test.go, x/participation/keeper/used_allocations_test.go
=> fix(`participation`): return 0 for `usedAllocations` query when address is valid but no entry is found

localnet/genesis_template.json
=> fix(`localnet`): remove additional comma in `genesis_template.json`

x/participation/keeper/grpc_auction_used_allocations.go, x/participation/keeper/grpc_auction_used_allocations_test.go
=> fix(`participation`): use address in `ListAuctionUsedAllocations` query

x/campaign/keeper/invariants.go, x/campaign/keeper/invariants_test.go
- Remove `CampaignChainsWithoutCampaignInvariant` that doesn't reflect a critical state inconsistency
- Add some fixes to `CampaignSharesInvariant`
- Add tests for `CampaignSharesInvariant`
=> refactor(`campaign`): improve and fix invariants

x/campaign/keeper/grpc_campaign_summary.go, x/campaign/keeper/keeper.go, x/launch/keeper/msg_settle_request_test.go, x/launch/keeper/request.go, x/launch/keeper/request_test.go, x/launch/keeper/validator_set_test.go, x/launch/types/msg_trigger_launch_test.go, x/launch/types/params_test.go, x/launch/types/request_content_test.go
Part of https://github.com/tendermint/spn/issues/687
- Removes a duplicated `Counter` function
- Increases coverage of mentioned files
=> test(`launch`): tests coverage

x/reward/keeper/reward_distribution_test.go, x/reward/types/genesis_test.go, x/reward/types/reward_pool_test.go
- Add coverage to remaining files in `x/reward`
=> test(`reward`): add coverage

x/claim/types/claim_record_test.go
Remove context initialization in TDT
=> test(`claim`): improve `ClaimRecord` validate

config.yml
=> fix(`config.yml`): denom metadata

config.yml
Sample genesis state for experimentation purposes
Part of https://github.com/tendermint/spn/issues/862
=> chore(`config.yml`): add `claim` sample genesis state

localnet/readme.md, localnet/spn/genesis_template.json, localnet/testnet/genesis_template.json
Include changes from `campaign` and `mint` modules in genesis templates
=> chore: some localnet fixes

readme.md
Update the `README` file:
- remove most of the `ignite` boilerplate
- add badges
- update URLs
We should make an issue for further updating this file, as this is just a good starting point.  If we like this, we could add similar badges to the ignite CLI repo
=> docs: update `README`

.github/PULL_REQUEST_TEMPLATE.md
- fix a small typo in the PR template markdown
=> chore(`docs`): fix PR template typo

x/launch/client/cli/query.go, x/reward/client/cli/query_reward_pool_test.go, x/reward/genesis_test.go, x/reward/keeper/grpc_params_test.go, x/reward/keeper/grpc_reward_pool_test.go, x/reward/keeper/invariants_test.go, x/reward/keeper/msg_set_reward_test.go, x/reward/keeper/reward_distribution_test.go, x/reward/simulation/store_test.go, x/reward/types/genesis_test.go, x/reward/types/msg_set_reward_test.go, x/reward/types/reward_pool_test.go
=> test(`reward`): normalize tests

x/launch/client/cli/query.go, x/monitoringp/genesis_test.go, x/monitoringp/keeper/begin_block_test.go, x/monitoringp/keeper/connection_channel_id_test.go, x/monitoringp/keeper/consumer_client_id_test.go, x/monitoringp/keeper/grpc_connection_channel_id_test.go, x/monitoringp/keeper/grpc_consumer_client_id_test.go, x/monitoringp/keeper/grpc_monitoring_info_test.go, x/monitoringp/keeper/grpc_params_test.go, x/monitoringp/keeper/handshake_test.go, x/monitoringp/keeper/monitoring_info_test.go, x/monitoringp/keeper/params_test.go, x/monitoringp/types/genesis_test.go, x/monitoringp/types/params_test.go
=> test(`monitoringp`): normalize tests

x/launch/client/cli/query.go, x/participation/client/cli/query_auction_used_allocations_test.go, x/participation/client/cli/query_used_allocations_test.go, x/participation/genesis_test.go, x/participation/keeper/auction_used_allocations_test.go, x/participation/keeper/available_allocations_test.go, x/participation/keeper/grpc_auction_used_allocations_test.go, x/participation/keeper/grpc_available_allocations_test.go, x/participation/keeper/grpc_params_test.go, x/participation/keeper/grpc_total_allocations_test.go, x/participation/keeper/grpc_used_allocations_test.go, x/participation/keeper/invariants_test.go, x/participation/keeper/msg_participate_test.go, x/participation/keeper/msg_withdraw_allocations_test.go, x/participation/keeper/params_test.go, x/participation/keeper/registration_period_test.go, x/participation/keeper/total_allocations_test.go, x/participation/keeper/used_allocations_test.go, x/participation/simulation/store_test.go, x/participation/types/genesis_test.go, x/participation/types/msg_participate_test.go, x/participation/types/msg_withdraw_allocations_test.go, x/participation/types/params_test.go, x/participation/types/tier_test.go
=> test(`participation`): normalize tests

go.mod, go.sum
=> chore: update `ibc-go` to `v5`

cmd/root.go, x/campaign/keeper/campaign_chains_test.go, x/campaign/keeper/msg_create_campaign_test.go
=> refactor: remove wasm config
