- x/genesis/client/cli/query.go
- x/genesis/client/cli/tx.go
Add CLI commands to approve and reject proposals, list approved and rejected proposals and print the current genesis.
Overview of the commands:
```
Chains:
spnd tx genesis create-chain <chain-id> <source-url> <source-hash> <genesis-path> --from user1 --keyring-backend test --chain-id spn --gas 300000
spnd q genesis list-chains
spnd q genesis show-chain <chain-id> [—save-genesis <genesis-path>]
Proposals:
spnd tx genesis proposal-add-account <chain-id> <tokens> --from user1 --keyring-backend test --chain-id spn
spnd tx genesis proposal-add-validator <chain-id> <peer> <gentx-path> --from user1 --keyring-backend test --chain-id spn --gas 300000
spnd q genesis show-proposal <chain-id> <proposal-id>
spnd q genesis approved-proposals <chain-id>
spnd q genesis pending-proposals <chain-id>
spnd q …
```
> feat(genesis): Add remaining CLI commands

- config.yml
- integration/env_test.go
Change the default ports used by the `spn` blockchain
> refactor: change the default ports for the blockchain

- x/genesis/types/proposal_add_account.go
- x/genesis/types/proposal_test.go
Verify that the address provided to `MsgProposalAddAccount` contains a valid Bech32 format
> fix(genesis): MsgProposalAddAccount verify address

- x/chat/keeper/channel_test.go
- x/chat/keeper/message_test.go
- x/chat/keeper/tag_reference_test.go
- x/chat/types/channel_test.go
- x/chat/types/message_test.go
- x/chat/types/messages_test.go
- x/chat/types/poll_test.go
- x/genesis/types/chain_test.go
- x/identity/keeper/keeper_test.go
- x/identity/types/messages_test.go
Remove all description strings in `require` statement. These strings don't provide additional information when the test fail and complicate the visibility of the code
> test: remove require statement descriptions

- config.yml
- integration/env_test.go
Push back the default port configuration since it's easier for local testing and we will be used remote machine for other works
> chore: push back default port config

- x/genesis/keeper/approval.go
- x/genesis/keeper/approval_test.go
Add the peer in chain information so that all peers can be fetched with `ShowChain`
> fix(genesis): add peer in the chain information when a validator is approved

- internal/testing/mock_genesis.go
- x/genesis/handler_test.go
- x/genesis/keeper/account.go
- x/genesis/keeper/account_test.go
- x/genesis/keeper/approval.go
- x/genesis/keeper/approval_test.go
For approving a validator: verify that the associated account has enough funds for the self-delegation. If not, deny the approval for the add validator proposal
> feat(genesis): verify account funds for validator self-delegation

- x/genesis/handler.go
We need to use sdk error type (`sdkerrors.ErrInvalidRequest`) to have the error correctly printed to the user on failed tx
> fix(genesis): explicit error message on failed tx

- x/genesis/client/cli/tx.go
- x/genesis/handler_test.go
- x/genesis/keeper/gprc_query_test.go
- x/genesis/types/messages.go
Omit to remove the `genesis` param in `NewMsgChainCreate` from #79
> fix: remove genesis param from NewMsgChainCreate

- x/genesis/keeper/gprc_query_test.go
- x/genesis/keeper/grpc_query.go
Sort the pending proposals so that the user can them in the order they have been created.
Improve the tests of proposals a bit
> fix(genesis): sort pending proposals from list-proposals query

- .ansible/roles/cosmos-faucet/defaults/main.yml
- .ansible/roles/cosmos-faucet/templates/faucet.service.j2
Reverts tendermint/spn#109
Trig deployment with `keyring-password` enabled.
> Revert "fix(ansible/faucet): use keyring backend test"

- .github/workflows/lint.yml
- .github/workflows/test-unit.yml
- .golangci.yml
- internal/parseint/parse.go
- internal/parseint/parse_test.go
- internal/testing/mock_genesis.go
- internal/testing/mock_identity.go
- internal/utils/parse.go
- internal/utils/parse_test.go
- x/identity/client/cli/tx.go
- x/identity/client/rest/rest.go
- x/launch/client/cli/query.go
- x/launch/client/cli/tx.go
- x/launch/handler.go
- x/launch/keeper/approval.go
- x/launch/keeper/grpc_query.go
- x/launch/keeper/querier.go
- x/launch/types/chain.go
- x/launch/types/messages.go
- x/launch/types/proposal.go
- x/launch/types/proposal_add_account.go
- x/launch/types/proposal_add_validator.go
- x/launch/types/proposal_change.go
Changes are straightforward and only addressing reported issues.
I disabled `interfacer` linter, as it doesn't always report relevant things,
also disabled rule G404: weak randomness linter, it recommends using crypto.Rand
even when it is unnecessary.
closes: https://github.com/tendermint/spn/issues/119
> fix: address linter issues and enable github action with linter

- Makefile
remove exclude rules from the lint inside the makefile `lint` command
> fix(Makefile): remove exclude rules from the lint make command

- x/profile/types/genesis.go
- x/profile/types/genesis_test.go
Closes #192
Add genesis validation to check if  the state is inconsistent if the value of the count is not strictly above all ids of the element of the list (since this value is incremented for each new value)
> feat(x/profile): add coordinator count check in genesis validate

- x/profile/keeper/coordinator.go
The count value is prefixed twice in the store with the prefix `CoordinatorCountKey`
> fix(profile): coordinator count value prefixed twice

- pkg/errors/critical.go
- x/launch/keeper/msg_server_request_add_account_test.go
- x/launch/keeper/msg_server_request_add_vested_account_test.go
- x/launch/keeper/msg_server_request_remove_account_test.go
- x/launch/keeper/msg_server_request_remove_validator_test.go
- x/launch/keeper/msg_server_settle_request_test.go
- x/launch/keeper/request_test.go
- x/launch/types/message_request_add_account_test.go
- x/launch/types/message_request_add_vested_account_test.go
- x/launch/types/message_request_remove_account_test.go
- x/launch/types/message_request_remove_validator_test.go
- x/launch/types/message_settle_request_test.go
- x/launch/types/vesting_options_test.go
- x/profile/keeper/msg_server_create_coordinator_test.go
- x/profile/keeper/msg_server_delete_coordinator_test.go
- x/profile/keeper/msg_server_delete_validator_test.go
- x/profile/keeper/msg_server_update_coordinator_address_test.go
- x/profile/keeper/msg_server_update_coordinator_description_test.go
- x/profile/types/genesis_test.go
- x/profile/types/message_create_coordinator_test.go
- x/profile/types/message_delete_coordinator_test.go
- x/profile/types/message_delete_validator_test.go
- x/profile/types/message_update_coordinator_address_test.go
- x/profile/types/message_update_coordinator_description_test.go
- x/profile/types/message_update_validator_description_test.go
Assert only the error type using the `require.ErrorIs` method from `testify` and remove the error message assertion.
```shell
$ make test
```
> refactor(tests): Assert only the error type using the `require.ErrorIs` method

- .codecov.yml
Remove the `codecov/patch` status from the CI since it is not necessary and sometime fails. We use codecov to get an absolute view of the coverare
> ci: disable codecov/patch status

- testutil/sample/campaign.go
- x/campaign/types/share.go
- x/campaign/types/shares.go
- x/campaign/types/shares_test.go
`Shares` simply reuse the type `sdk.Coins` since it represents denoms associated with an amount.
We add here the prefix `s/` to distinguish it from other coins in the store
> feat(campaign): create `shares` type

- app/simulation_test.go
Reduce `FlagBlockSizeValue` to prevent insufficient gas error to occur during simulation tests until we figure out: https://github.com/tendermint/spn/issues/369
> test(`simapp`): reduce block size

- x/launch/types/genesis.go
As needed for the `network init` command refactor
> refactor(`launch`): set initial launch ID counter to `1`

- config.yml
Set `spn` as token denom option for module like `crisis` constant fee
> chore: set `spn` as the default token denom for all usage

- config.yml
- go.mod
- go.sum
`minLaunchTime` param defines the minimal delay that the coordinator can choose between trigger  launch and the genesis time to let validators prepare their node
This value is currently set to 1 day for real use case. We set it to 5 seconds in `config.yml` for test purpose and test Starport CLI
> chore: change `minLaunchTime` launch param to 5 in `config.yml`

- x/launch/types/params.go
Set a temporary value for `DefaultMinLaunchTime` of 5 secondes for test purpose since the Starport config is sometime not used by all tools we use
> refactor(`launch`): set temporary params `DefaultMinLaunchTime`

- x/campaign/keeper/campaign.go
- x/launch/keeper/genesis_validator.go
- x/launch/keeper/validator_set.go
- x/launch/types/key_request.go
- x/monitoringc/keeper/handshake_test.go
- x/monitoringc/types/key_launch_id_from_channel_id.go
- x/monitoringc/types/key_provider_client_id.go
- x/monitoringc/types/key_verified_client_id.go
- x/monitoringp/keeper/handshake_test.go
- x/monitoringp/module.go
- x/monitoringp/types/codec.go
- x/profile/keeper/coordinator.go
- x/reward/types/codec.go
- Use `UintBytes` helper method to make uint64 to byte slice conversion
- Fix some lint issues
> refactor: use `UintBytes` helper to convert uint64 keys

- Makefile
Add a step in the `make format` step to run `goimports` along with the existing step of running `gofmt`.  Occasionally, the linter complains about `goimports` errors, so adding this will take care of those issues automatically.
Run the new `make format` command.
If we want this minor addition, we can run `make format` on the repo and add this in a separate PR.  It will just modify the layout of the imports a bit, but will change almost all files in that way.
> chore: goimports added to format

- localnet/genesis_template.json
Add the new `SupplyRange` param of `campaign` in localnet genesis template with the current default values
> chore: add supply range param for localnet genesis

- x/campaign/module_simulation.go
Closes #553 
Fix a wrong format for `TotalSupplyRange` param in `RandomizedParams` for `campaign/module_simulation.go`. 
Run `starport chain simulate` with the following modifications made to `app/simulation_test.go`:
```golang
func BenchmarkSimulation(b *testing.B) {
simapp.FlagEnabledValue = true
simapp.FlagNumBlocksValue = 2000
simapp.FlagBlockSizeValue = 100
simapp.FlagCommitValue = true
simapp.FlagPeriodValue = 10
simapp.FlagVerboseValue = true
```
Error reported in #553 should not appear now.
> fix(`campaign`): properly format `TotalSupplyRange` for param change simulation

- x/monitoringc/keeper/msg_server_create_client_test.go
- x/monitoringp/keeper/begin_block.go
- x/monitoringp/keeper/begin_block_test.go
- x/monitoringp/module.go
Closes #564
Skip the `BeginBlock()` function in `x/monitoringp/module.go` when BlockHeight == 1.  I'm not sure how to test this other than recreating the scenario described in the issue.  Any thoughts are welcome.
> feat(`monitoringp`): skip block height 1 in begin-blocker

- x/monitoringc/module_ibc.go
- x/monitoringc/types/keys.go
- x/monitoringp/module_ibc.go
- x/monitoringp/types/keys.go
Set `monitoring-1` for the version of the module.
Relayer connection works from Hermes `0.12.0` https://github.com/informalsystems/ibc-rs/releases/tag/v0.12.0
(there was an issue with custom version in previous releases)
> feat(`monitoring`): add versions for module handshake

- x/campaign/simulation/simulation.go
- x/launch/simulation/simulation.go
Closes #652
Add a balance check to `SimulateCreateCampaign` and `SimulateCreateChain` that also includes checking the account balance is enough to cover the creation fee as well as a pre-calculated random gas fee.
`make test-sim-profile` does not run into the issue described in the attached issue, but there are still simulation issues to be dug into.
> fix(`simulation`): add fee checks

- x/campaign/client/cli/query_campaign_summary.go
- x/campaign/simulation/simulation.go
- x/campaign/types/expected_keepers.go
- x/launch/keeper/request_test.go
Add a new test for `keeper.CheckAccount()`.  I was investigating these functions for our simulation issues and realized we did not have a test for this function.
> test(`launch`): CheckAccount test

- testutil/sample/campaign.go
`CampaignGenesisState` from `sample` contains campaigns initialized with empty allocated shares and mainnet accounts containing shares.
This genesis state was inconsistent because the sum of shares allocated for accounts must be tracked by the `AllocatedShares` value of the campaign
This PR removes the accounts for a quick fix. A further change can include adding accounts with the allocated correctly tracked for better entropy
> fix(`campaign`): fix sample genesis with inconsistent state

- go.mod
- go.sum
Closes #<issue number>. _in case of a bug fix, this should point to a bug or any other related issue(s)_
- Bumps the `fundraising` module to `v0.2.0`.  Previously we were using a cherry-picked commit.
> chore: bump fundraising module version

- testutil/sample/campaign.go
- testutil/sample/participation.go
- testutil/sample/profile.go
- x/campaign/genesis_test.go
- x/campaign/keeper/invariants.go
- x/campaign/keeper/invariants_test.go
- x/campaign/keeper/total_shares_test.go
- x/campaign/types/share_vesting_options_test.go
- x/campaign/types/shares_test.go
- x/participation/genesis_test.go
- x/participation/keeper/grpc_available_allocations_test.go
- x/participation/keeper/grpc_total_allocations_test.go
- x/participation/keeper/msg_participate_test.go
- x/participation/keeper/total_allocations.go
- x/participation/types/genesis_test.go
- x/participation/types/params_test.go
- x/profile/types/genesis_test.go
Part of #687
Increase code coverage of the modules above with the excetpion of `keeper/grpc_params` (for `campaign` and `participation`) that are handled by @ludtb in #700
> test: increase code coverage for `campaign`, `participation` and `profile`

- x/campaign/module_simulation.go
> test(`campaign`): add `SimulateMsgUpdateTotalSupply` to `WeightedOperation` in simulation

- app/simulation_test.go
- app/simutil/app_state.go
Closes #720
Ensure there is no `int64` overflow when generating the initial bank state.  The maximum amount of coins per account is `int64Max / totalNumAccounts`.
> fix(`simulation`): ensure no int overflow for bank state generation

- x/profile/simulation/simulation.go
Closes #725
- Add check to ensure that sim addresses are not the same
> fix(`profile`): ensure addresses are not equal for MsgAddValidatorOperatorAddress sim

- .gitignore
- app/simulation_test.go
- testutil/sample/campaign.go
- testutil/sample/launch.go
- testutil/sample/simulation.go
- testutil/simulation/util.go
- x/campaign/simulation/simulation.go
- x/launch/simulation/simulation.go
- x/participation/keeper/msg_participate.go
- x/participation/keeper/registration_period.go
- x/participation/keeper/registration_period_test.go
- x/participation/simulation/simulation.go
- x/participation/simulation/store.go
- x/participation/simulation/store_test.go
- x/profile/simulation/simulation.go
- x/reward/keeper/reward_distribution_test.go
- x/reward/simulation/simulation.go
Closes #369 
This PR does not really fix #369, as explained in the issue itself.
However, we at least switch over using only the `sdk.DefaultBondDenom` coin for fees in our modules' simulation.
Problem will stil exist however for modules we pull from the cosmos-sdk, so `out of gas` will still occasionally occur (and it's highly likely to occur for large simulations), but I propose we close #369 as this can't really be avoided.
I've also made sure we initialize the `rand` seed in `TestAppStateDeterminism`, and fixed an error in how we were selecting auctions for `msgParticipate` simulation. 
Apologies if I may have bundled too many things together in this PR.
> test: ensure only `sdk.DefaultBondDenom` is used for fees in our modules simulation

- x/participation/keeper/registration_period.go
Follow a lint suggestion to simplify the return statement in `IsRegisterEnabled()` in the `participation` module.
> chore(`participation`): simplify IsRegisterEnabled return statement

- go.mod
- go.sum
- x/campaign/keeper/grpc_campaign_summary.go
- x/campaign/keeper/keeper.go
- x/launch/keeper/request.go
Implement a method `GetRequestCount` to get the number of requests instead of relying on the request counter that is used for determining the request ID
This count method iterates elements, in the store eventually we want to optimize this logic by adding a new entry in the store
> fix(`campaign`): return correct request number in campaign summary

- go.mod
- go.sum
- x/campaign/module_simulation.go
- x/campaign/simulation/simulation.go
Remove it since `bank` simulation perform sending coins operation
> chore: remove `SendVoucher` operation in simulation

- go.mod
- go.sum
Bump sdk `v0.45.3` -> `v0.45.4`
> chore: sdk-bump

- .github/workflows/reset-testnet.yml
Adds an hack to testnet reset action to support newest cosmos-sdk changes.
These are the criteria that every PR should meet, please check them off as you
review them:
> ci(reset-testnet): add hack to reset testnets

- config.yml
Closes #761
Update the `config.yml` to add denom metadata to the chain.  
- inspect the genesis state after running `ignite chain serve`
```json
"denom_metadata": [
{
"description": "The native staking token of Starport Network",
"denom_units": [
{
"denom": "uspn",
"exponent": 0,
"aliases": [
"millispn"
]
},
{
"denom": "mspn",
"exponent": 3,
"aliases": [
"microspn"
]
},
{
"denom": "spn",
"exponent": 6,
"aliases": []
}
],
"base": "uspn",
"display": "spn",
"name": "Starport Network",
"symbol": "SPN"
}
]
},
```
- query
```shell
spnd query bank denom-metadata
metadatas:
- base: uspn
denom_units:
- aliases:
- millispn
denom: uspn
exponent: 0
- aliases:
- microspn
denom: mspn
exponent: 3
- aliases: []
denom: spn
exponent: 6
description: The native staking token of Starport Network
display: spn …
```
> feat: denom metadata

- x/campaign/keeper/mainnet_account.go
- x/campaign/keeper/mainnet_vesting_account.go
- x/campaign/types/genesis.go
- x/campaign/types/keys.go
- x/launch/keeper/genesis_account.go
- x/launch/keeper/genesis_validator.go
- x/launch/keeper/vesting_account.go
- x/launch/types/genesis.go
- x/launch/types/keys.go
Factorize different methods with similar logic in `key.go` to retrieve account key path.
Unique method is named `AccountKeyPath`
> refactor: factorize similar store key methods

- app/app.go
Fix lint error based on cosntant name format in `app.go`
> fix: app.go const lint

- x/claim/types/claim_record.go
- x/launch/keeper/genesis_validator.go
- x/launch/keeper/genesis_validator_test.go
- x/launch/keeper/validator_set.go
- x/mint/keeper/keeper.go
- x/participation/keeper/total_allocations.go
- x/reward/keeper/reward_distribution.go
Remove all uses of the `sdk.Int.ToDec()` function.  This function is removed in SDK `v0.46.0`.  Conversion between `sdk.Int` and `sdk.Dec` can be done using `sdk.NewDecFromInt()`.
Part of #909
These are the criteria that every PR should meet, please check them off as you
review them:
> refactor: remove usage of `ToDec()`

- config_2.yml
Set custom binary name in `config_2.yml` to make usage of local `spn` working when launching `spn`
The reason for this is that the local `spn` instance and the `spn` to launch could have different versions
If cli interface is not compatible, usage of network command fails because the `spnd` command from the `spn` to launch built binary will be run with the incompatible keyring of the `spn` instance
> chore: set binary name in config_2.yml

- go.mod
- go.sum
Updates the fundraising package to the newly released `v0.3.1`.  This version of the packages includes all of the latest updates for `v0.46.x`.  This removes the `replace` clause in our `go.mod` that was redirecting to my fork of `fundraising`.
> chore: update to latest `fundraising`

- app/export.go
- docs/docs.go
- x/launch/client/cli/tx_create_chain.go
- x/launch/client/cli/tx_request_add_validator.go
Removes usage of `io/ioutil` package from the codebase.  This package has been deprecated since go `1.16` and has equivalent functions in other package (namely `os` and `io`).
> chore: remove `io/ioutil`

- x/launch/client/cli/query.go
- x/monitoringc/client/cli/query_launch_id_from_channel_id_test.go
- x/monitoringc/client/cli/query_monitoring_history_test.go
- x/monitoringc/client/cli/query_provider_client_id_test.go
- x/monitoringc/client/cli/query_verified_client_ids_test.go
- x/monitoringc/genesis_test.go
- x/monitoringc/keeper/grpc_launch_id_from_channel_id_test.go
- x/monitoringc/keeper/grpc_monitoring_history_test.go
- x/monitoringc/keeper/grpc_params_test.go
- x/monitoringc/keeper/grpc_provider_client_id_test.go
- x/monitoringc/keeper/grpc_verified_client_ids_test.go
- x/monitoringc/keeper/invariants_test.go
- x/monitoringc/keeper/launch_id_from_channel_id_test.go
- x/monitoringc/keeper/launch_id_from_verified_client_id_test.go
- x/monitoringc/keeper/monitoring_history_test.go
- x/monitoringc/keeper/monitoring_packet_test.go
- x/monitoringc/keeper/params_test.go
- x/monitoringc/keeper/provider_client_id_test.go
- x/monitoringc/keeper/verified_client_id_test.go
- x/monitoringc/types/genesis_test.go
- x/monitoringc/types/msg_create_client_test.go
> test(`monitoringc`): normalize tests

- pkg/types/constant.go
- scripts/metadata_sample.yml
- scripts/populate.sh
- x/launch/client/cli/tx_create_chain.go
- add `metadata-file` flag to specify a file for chain metadata content in create chain command
- increase metadata max length to `1000`
- add in `populate.sh` script a chain with metadata for launchpad overview
> feat(`launch`): improve capability for chain metadata

- scripts/metadata_sample.yml
Add the logo and cover added in `example project`
> chore: add logo and cover in sample metadata

- scripts/metadata_sample.yml
Update yet another time to support the new logo and cover extension
> chore: update metadata sample with new logo and cover
